### ISSUE TITLE
yaml error line 397

### ISSUE THREAD

**Issue by kroon040** [albert-canfield/HA-panel-esphome#2]
Hi,

I was trying to install your yam, but i got this error

ERROR Error while reading config: Invalid YAML syntax:

while scanning a simple key
  in "ha-panel.yaml", line 397, column 13
could not find expected ':'
  in "ha-panel.yaml", line 398, column 23

Any idea what cause this?

It looks like this

            widgets:h

**Comment by albert-canfield** [comment]
Hi,

It shouldn't have the "h" after the "widgets:" Could it be a typo on your code?

 ```
            bg_opa: TRANSP
            border_opa: TRANSP
            widgets:
              - button:
                  id: boiler_heating_btn
                  checkable: true 
```
