### ISSUE TITLE
Using HA the Days of the Week (Monday, Tuesday...) 

### ISSUE THREAD

**Issue by albert-canfield** [albert-canfield/HA-panel-esphome#6]
I did that by creating this template sensor on my configuration.yaml that every 00:00 or every time HA restarts set the nominal week day:

```
template:
  - trigger: 
    - platform: time
       at: "00:00:00"
    - platform: homeassistant
       event: start
    sensor:
       - unique_id: week_day
          name: "Week Day"
         state: >-
            {{ now().strftime('%A') }}
```

Then, on the HA Panel/Deck yaml, you need to add a new LABEL to capture it

```
- label:
            align: CENTER
            id: display_week_day
            text: weekday
            text_font: roboto24
            text_color: 0xFFFFFF
            y: -100
            x: -75
```

and a new TEXT SENSOR that will get the week day from HA

```
- platform: homeassistant
    id: ha_week_day
    entity_id: sensor.week_day
    on_value:
      then:
        - lvgl.label.update:
            id: display_week_day
            text: !lambda return id(ha_week_day).state.c_str();
```

_Originally posted by @albert-canfield in https://github.com/albert-canfield/HA-panel-esphome/issues/4#issuecomment-2294392045_
